services:
  labweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Redis__ConnectionString=redis:6379
      - ElasticsSettings__Url=http://elasticsearch:9200
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - elk